#!/bin/bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
  echo ""
  echo "closing rails"
  kill -INT ${T3}
  echo "closing sidekiq"
  kill -INT ${T2}
  wait ${T3}
  echo "rails closed"
  wait ${T2}
  echo "sidekiq closed"
  echo "closing redis"
  kill -INT ${T1}
  wait ${T1}
  echo "redis closed, exiting"
  exit 0
}

echo "------------------"
echo "starting redis"
redis-server > /dev/null &
T1=${!}
echo "redis started"
echo "starting sidekiq"
bundle exec sidekiq > /dev/null &
T2=${!}
echo "sidekiq started"
echo "starting rails"
rails s > /dev/null &
T3=${!}
echo "rails started"
echo "------------------"
echo "The website is now online, to close it, use Ctrl+C"
wait ${T1}
wait ${T2}
wait ${T3}