class CreateStats < ActiveRecord::Migration[6.1]
  def change
    create_table :stats, id:false do |t|
      t.integer :id
      t.integer :number
      t.integer :preferredSlot
      t.string :givenName
      t.string :name
      t.string :familyName
      t.string :role
      t.string :headshotUrl
      t.string :eroe
      t.integer :abilityDamageDone
      t.integer :accretionKills
      t.integer :amplificationMatrixAssists
      t.integer :barrageKills
      t.integer :bioticGrenadeKills
      t.integer :blizzardKills
      t.integer :bobKills
      t.integer :carnageKills
      t.integer :chainHooksAttempted
      t.integer :chargedShotKills
      t.integer :coalescenseHealing
      t.integer :concussionMineKills
      t.integer :criticalHits
      t.integer :damageAmplified
      t.integer :damageBlockedSojurn
      t.integer :damageDiscordOrb
      t.integer :damageTaken
      t.integer :deadeyeKills
      t.integer :deathBlossomKills
      t.integer :deaths
      t.integer :dragonbladeKills
      t.integer :dragonstrikeKills
      t.integer :earthshatterKills
      t.integer :earthshatterStuns
      t.integer :eliminations
      t.integer :enemiesChainHooked
      t.integer :enemiesEMPd
      t.integer :enemiesFrozen
      t.integer :enemiesHacked
      t.integer :enemiesSlept
      t.integer :energyMax
      t.integer :finalBlows
      t.integer :focusingBeamKills
      t.integer :graviticFluxKills
      t.integer :gravitonSurgeKills
      t.integer :healingDone
      t.integer :helixRocketKills
      t.integer :heroDamageDone
      t.integer :immortalityFieldDeathsPrevented
      t.integer :inspireUptime
      t.integer :jaggedBladeKills
      t.integer :javelinDamage
      t.integer :jumpPackKills
      t.integer :kitsuneRushAssists
      t.integer :knockbackKills
      t.integer :kunaiKills
      t.integer :lifetimeEnergyAccumulation
      t.integer :meteorStrikeKills
      t.integer :moltenCoreKills
      t.integer :negativeEffectsCleansed
      t.integer :overclockKills
      t.integer :overhealthProvided
      t.integer :piledriverKills
      t.integer :playersKnockedBack
      t.integer :playersResurrected
      t.integer :playersTeleported
      t.integer :primalRageKills
      t.integer :pulseBombKills
      t.integer :pulseBombsAttached
      t.integer :ripTireKills
      t.integer :rocketDirectHits
      t.integer :scopedCriticalHitKills
      t.integer :scopedCriticalHits
      t.integer :scopedHits
      t.integer :selfdestructKills
      t.integer :shotsHit
      t.integer :soloKills
      t.integer :stickyBombsKills
      t.integer :stormArrowKills
      t.integer :tacticalVisorKills
      t.integer :terraSurgeKills
      t.integer :timePlayed
      t.integer :timeSpentOnFire
      t.integer :turretKills
      t.integer :ultimatesNegated
      t.integer :ultsEarned
      t.integer :ultsUsed
      t.integer :wholeHogKills

      t.timestamps
    end
  end
end
